before_script:
  - pip install virtualenv
  - virtualenv -p "$(which python)" /tmp/test

.run_script: &run_script
  script:
    - source /tmp/test/bin/activate

    - pip install .

    - python setup.py test --addopts="--backend openwrt --backend mock"

test_python3:
  image: registry.nic.cz/turris/foris-ci/python3
  <<: *run_script

flake8:
  image: registry.nic.cz/turris/foris-ci/python3
  script:
    - python setup.py flake8
